# -*- coding: utf-8 -*-
"""CA1- Question 4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yI5y5nKAgqBWlgZ-OzowEdYQ1EV_lqij
"""

print('##############################################')
print('              MYPY PHONE BOOK                 ')
print('##############################################')

phone_directory = {}

def Add_contact(person_name, phone_number):
    if phone_number in phone_directory.values():
        print("Error: Phone number already exists.")
    else:
        phone_directory[person_name] = phone_number
        print("Contact added:",person_name, phone_number)

def Delete_contact(phone_number):
    for name, phone in phone_directory.items():
        if phone == phone_number:
            del phone_directory[name]
            print("Contact removed:",name,phone)
            return
    print("Error: Phone number not found.")

def Update_contact(person_name, phone_number):
    if phone_number in phone_directory.values():
        print("Error: Phone number already exists.")
    elif person_name not in phone_directory:
        print("Error: Name not found.")
    else:
        phone_directory[person_name] = phone_number
        print("Contact updated:",person_name, phone_number)

def Lookup_contact(phone_number):
    for name, phone in phone_directory.items():
        if phone == phone_number:
            print("Name:" ,name, "Phone:", phone)
            return
    print("Phone number not found.")
    option = input("Do you want to Add this contact? (Yes/No): ")
    if option == "Yes":
        name = input("Enter name: ")
        Add_contact(name, phone_number)

while True:
        print("\nMYPY Phone Book System")
        print("1. Add Contact")
        print("2. Delete Contact")
        print("3. Update Contact")
        print("4. Lookup Contact")
        print("5. Quit")

        choice = input("Enter your choice: ")

        if choice == "1":
            name = input("Enter name: ")
            number = input("Enter phone number: ")
            Add_contact(name,number)
        elif choice == "2":
            number = input("Enter phone number to Delete: ")
            Delete_contact(number)
        elif choice == "3":
            name = input("Enter name to Update: ")
            number = input("Enter new phone number: ")
            Update_contact(name,number)
        elif choice == "4":
            number = input("Enter phone number to search: ")
            Lookup_contact(number)
        elif choice == "5":
            print("Exiting program.")
            break
        else:
            print("Invalid choice. Please try again.")