# -*- coding: utf-8 -*-
"""CA1-Question 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DaFu8A1TGW-sEJ8Q2wgN7zn2Go_tFcgd
"""

print('#####################################################')
print('              WELCOME TO DBS CONSOLE                 ')
print('#####################################################')
Input_name = input("Enter your username in the format Domain_name\\Username: ")
Domain_name, username = Input_name.split('\\')
print("Domain : ", Domain_name)
print("Username : ", username)