# -*- coding: utf-8 -*-
"""CA1-Question 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uPZ1x22rD5wdXx9LdfzaRxhNyQehz-ox
"""

def integer_value(numbers):
  count = {}
  for num in numbers:
    if num in count:
      count[num] += 1
    else:
      count[num] = 1
  return count

integers = []
counter = 1

print("Enter the value to check frequency or 'QUIT to exit")

while True:
  Integer = input("Enter the integer: ")
  if Integer.upper() == 'QUIT':
    break
  integers.append(Integer)
  counter+=1

count = integer_count(integers)
print()
print("Frequency of each Number is:")
for num, freq in count.items():
  print(f"Number: {num}, Frequency: {freq}")