# -*- coding: utf-8 -*-
"""CA1- Question 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nCynWdOSkIrnkL71jZrOLLy5YiKd73eX
"""

#Employee Data
Employee_name=input("Enter your name:\n")
Employee_number=input("Enter your Employee Number:\n")
Week_Ending=input("Enter the Week ending date:\n")
Hours_Worked=float(input("Enter the number of hours worked:\n"))
Rate_Per_Hour=float(input("Enter the rate per hour:\n"))
Standard_Tax_Rate=float(input("Enter Standard tax rate:\n"))
Overtime_Tax_Rate=float(input("Enter Overtime tax rate:\n"))

#working hours & overtime details
Overtime_Rate=Rate_Per_Hour*1.5
Standard_working_hours=37.5
overtime_hours=Hours_Worked-37.5

if(Hours_Worked<37.5):
    Gross_Pay=Hours_Worked*Rate_Per_Hour
    Tax_Pay=Gross_Pay*Standard_Tax_Rate
    Net_Pay=Gross_Pay+Tax_Pay
elif (Hours_Worked>37.5):
        Gross_Pay=Rate_Per_Hour*37.5 #pay for hours less than 37.5 hours
        Tax_pay_1=Gross_Pay*Standard_Tax_Rate
        net_pay_1=Gross_Pay+Tax_pay_1
        Overtime_Pay=((Hours_Worked-37.5)*Overtime_Rate)
        Tax_pay_2=Overtime_Pay*Overtime_Tax_Rate
        net_pay_2=Overtime_Pay+Tax_pay_2
        Tax_Pay=Tax_pay_1+Tax_pay_2
        Net_Pay=net_pay_1+net_pay_2

#printing the payslip
print("                               PAYSLIP                          ")
print("Week Ending ",Week_Ending )
print("Employee:",Employee_name)
print("Employee Number:",Employee_number)

print("                               Earnings                     Deductions           ")
print("                            Hours   Rate   Total")
print("Hours (normal)               ",Hours_Worked,    Rate_Per_Hour,     Gross_Pay,     "Tax @",Standard_Tax_Rate, Gross_Pay*Standard_Tax_Rate  )
print("Hours (Overtime)             ",overtime_hours,  Overtime_Rate,     Overtime_Pay,  "Tax @",Overtime_Tax_Rate, ((Hours_Worked-37.5)*Overtime_Rate*Overtime_Tax_Rate))

print("                              Total Pay:",                                                                   Gross_Pay             )
print("                              Total Deductions:",                                                            Tax_Pay              )
print("                              Net Pay:",                                                                     Net_Pay)